# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBDriverWish.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBDriverWish.proto',
  package='PBDriverWish',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12PBDriverWish.proto\x12\x0cPBDriverWish\"J\n\x0cPBDriverWish\x12\x12\n\nleft_servo\x18\x01 \x01(\x05\x12\x13\n\x0bright_servo\x18\x02 \x01(\x05\x12\x11\n\ttop_servo\x18\x03 \x01(\x05\x62\x06proto3')
)




_PBDRIVERWISH = _descriptor.Descriptor(
  name='PBDriverWish',
  full_name='PBDriverWish.PBDriverWish',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='left_servo', full_name='PBDriverWish.PBDriverWish.left_servo', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right_servo', full_name='PBDriverWish.PBDriverWish.right_servo', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top_servo', full_name='PBDriverWish.PBDriverWish.top_servo', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['PBDriverWish'] = _PBDRIVERWISH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PBDriverWish = _reflection.GeneratedProtocolMessageType('PBDriverWish', (_message.Message,), {
  'DESCRIPTOR' : _PBDRIVERWISH,
  '__module__' : 'PBDriverWish_pb2'
  # @@protoc_insertion_point(class_scope:PBDriverWish.PBDriverWish)
  })
_sym_db.RegisterMessage(PBDriverWish)


# @@protoc_insertion_point(module_scope)
